#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/macbook/Downloads/flutter_3_24"
export "FLUTTER_APPLICATION_PATH=/Users/macbook/Documents/DATN2024/DoAnTotNghiep2024/fare_riding_app"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/macbook/Documents/DATN2024/DoAnTotNghiep2024/fare_riding_app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "CONFIGURATION_BUILD_DIR=/Users/macbook/Documents/DATN2024/DoAnTotNghiep2024/fare_riding_app/build/ios/iphoneos"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/macbook/Documents/DATN2024/DoAnTotNghiep2024/fare_riding_app/.dart_tool/package_config.json"
